title: Data Science Education Portal
email: vivrd@berkeley.edu
description: Educational resources for data science students and educators
baseurl: ""
url: "https://ca-datascience.github.io"

# Build settings
theme: minima