name: PR Build Check

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "1.4.550"

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: .

      - name: Upload preview artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr-preview-site
          path: ./_site
          retention-days: 7
